name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v5
  workflow_dispatch: # Run workflow manually
  repository_dispatch:
    types: [content-update] # Triggered by knowledge-garden repo

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Update Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote
      - name: Rename README.md in Submodule
        run: |
          cd content
          if [ -f README.md ]; then
            mv README.md index.md
          fi
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Install Quartz plugins
        run: npx quartz plugin install
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
